image: linux

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public

unittest:
  stage: test
  script:
    - npm install
    - npm install -D babel-core@7.0.0-bridge.0
    - npm test unit

deploy:
  stage: deploy
  script:
    - npm run build
    - cd build/
    - az webapp up -n lewayf -l northeurope