image: linux

stages:
  - build
  - test
  - deploy

buildapp:
  stage: build
  script:
  - npm install
  - npm run build
  - cp web.config build/
  artifacts:
    paths:
    - build
    - node_modules

unittest:
  stage: test
  script:
    - npm install -D babel-core@7.0.0-bridge.0
    - npm test unit
  dependencies:
    - buildapp

deploy:
  stage: deploy
  script:
    - cd build/
    - az webapp up -n lewayf -l northeurope
  dependencies:
    - buildapp
  only:
    - master