image: linux

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public

unittest:
  stage: test
  script:
    - npm install
    - npm test unit