language: node_js
node_js:
- '10.10.0'
script:
- npm install
- npm run test
deploy:
  on:
    branch: feature/migration
  provider: heroku
  api_key:
    secure: "f54a0f06-9e52-497f-b4e3-a5e5fd4a2133"
  app: lewayfinder


  