language: node_js
node_js:
- '10.10.0'
before_install:
- npm install
script:
- npm run test
- npm run build
deploy:
  on:
    branch: feature/migration
  provider: azure_web_apps
  username: $wf-frontend
  password: SYYz6nzGnAASmFn51BJeu4xFh0jRgzmAuksuhASLt95fpozqf0ssb48ZFkdo
  site: azure_deployment_sitename
  slot: azure_deployment_slotname