export const SET_SELECTED_PRODUCT = "SET_SELECTED";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const GET_SELECTED_PRODUCT = "GET_SELECTED";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";